FROM 771456714234.dkr.ecr.us-east-1.amazonaws.com/cruddur-python:3.10-slim-buster

WORKDIR /backend-flask

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

ENV FLASK_DEBUG=0
ENV PORT=4567

CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:4567", "app:app"]
